# Generated by Django 5.0.4 on 2024-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=8)),
                ('NameScript', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Loginform',
                'verbose_name_plural': 'Loginforms',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=60)),
                ('IAnum', models.IntegerField()),
                ('OSnum', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Plaintiffs', models.TextField()),
                ('Defendants', models.TextField()),
                ('pf1', models.CharField(max_length=300)),
                ('df1', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Suit',
                'verbose_name_plural': 'Suits',
            },
        ),
    ]
